#!/usr/bin/perl -n

# Created 3/30/2008
# This script was created to rename image directorys in the format
# of NameMMDDYYY into YYYYMMDDName. Why do this? So the directories
# sort themselves by date automatically with no additional magic 
# needed!

if ( /(\D+)(\d{2})(\d{2})(\d{4})/ ) { 
   $old_entry = $_;
#   print "Found this: name - $1, month = $2, day = $3, year = $4 \n";
   $name = $1;
   $month = $2;
   $day = $3;
   $year = $4;

   # modify what we need to
   chomp $old_entry;   
   $name =~ s/\s//;
   print "mv \"${old_entry}\" \"${year}${month}${day}${name}\" \n"; 
}
